### ISSUE TITLE
Doesnt normalize Danish ø

### ISSUE THREAD

**Issue by tsvetann** [motss/normalize-diacritics#108]
### Description
The `normalize-diacritics` does not work correctly with danish ø
When  running it on tromsø

### Expected outcome
tromso

### Actual outcome
tromsø

### Live Demo

n/a

### Versions of affected system

- **normalize-diacritics version**: 2.2.3
- **Node.js version**: 10.11
- **Platform details** _(macOS Sierra 10.13.6)_:

**Comment by motss** [comment]
@tsvetann Thanks for raising this interesting issue. For Danish characters, it does not count as characters with accents/ diacritics. I'll release a patch for such cases to avoid using the native `String.prototype.normalize`.

**Comment by motss** [comment]
For non-accented characters, i.e. [Latin-1 Supplement](https://bit.ly/2vz1l7m), native `String.prototype.normalize` basically does nothing as it does not find any accents/ diacritics in the character itself.

```js
// Accented character (õ) contains > 1 character during splitting
'\u00f5'.normalize('NFD').split('').length; // 2

// Non-accented character (ø) is always 1 character long
'\u00f8'.normalize('NFD').split('').length; // 1
```

**Comment by motss** [comment]
This has been fixed at https://github.com/motss/normalize-diacritics/commit/225110feeab095caf683e5dccebc86a5d2bc51d0 to always use string replacement with comparison using RegExp to replace all non basic Latin characters.

**Comment by tsvetann** [comment]
@motss Thanks for fixing this.
