### ISSUE TITLE
Bug due to RegExp lastIndex state

### ISSUE THREAD

**Issue by ppvg** [motss/normalize-diacritics#112]
Repeated letters with the same diacritic are not consistently normalized. E.g.:

```ts
> normalizeSync('éééé')
'eéeé'
> normalizeSync('åååå')
'aåaå'
> normalizeSync('éåéåéåéå')
'eaéaeaéa'
```

(Live demo: https://repl.it/repls/LeftFirsthandDatabases)

This bug is caused by the use of `RegExp.prototype.test` ([normalize-diacritics.ts#L131](https://github.com/motss/normalize-diacritics/blob/master/src/normalize-diacritics.ts#L131)), which keeps state when called on a regex that has the `/g`lobal flag;

> If the regex has the global flag set, `test()` will advance the `lastIndex` of the regex. A subsequent use of `test()` will start the search at the substring of `str` specified by `lastIndex`

_Source: [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test#Using_test()_on_a_regex_with_the_global_flag)._

**Comment by motss** [comment]
@ppvg Thanks for raising this issue. This is something I'm not aware of but I learnt from the mistake as of this issue.

After understanding the problem, that is how `/g` flag works and `lastIndex` will not get reset as long as we are using the same RegExp to do comparison. One way to fix this is to remove `/g` flag but this is not what I wanted.

By realizing the actual behavior and what I wanted is to not to reuse the same RegExp for comparison, so we can instead create a new RegExp for each comparison: `new RegExp(n.diacritics).test(s))`;
