### ISSUE TITLE
Question: Why an async version that is not doing any async stuff?

### ISSUE THREAD

**Issue by hacknlove** [motss/normalize-diacritics#117]
I don't get it. 

What is the reason of having this? In which scenario could be better to call this function instead of normaliceSync ?

```
export async function normalize(input?: string | null) {
  return normalizeSync(input);
}
```

**Comment by motss** [comment]
Good question.

It is by no means any better to use the async version. For completeness, both async and sync version is included. If sync version suits you, you should not force yourself to use the async version.

Hope this clarifies.
