### ISSUE TITLE
why dedupe?

### ISSUE THREAD

**Issue by erikKeresztes** [motss/normalize-diacritics#122]
why does this package run npm dedupe after install? i don't even use npm, this adds unnecessary delay when installing dependencies. i know you can disable postinstall scripts but i still think it should be removed from the package

**Comment by motss** [comment]
@erikKeresztes I'm not sure why that affects you. When you install the package, `postintall` script inside the package will not get executed in your own project. Kindly attach a screenshot or reproduction steps to help me to understand the issue.

**Comment by erikKeresztes** [comment]
@motss the docs say that postinstall does get executed whenever you run `npm install`, https://docs.npmjs.com/cli/v8/using-npm/scripts#npm-install
it's not as clear when using npm but pnpm makes it clearer
![image](https://user-images.githubusercontent.com/58667141/144323951-32290893-20b9-4a29-87c9-fd47f4813971.png)

**Comment by motss** [comment]
@erikKeresztes I've done some researches for this issue and found out that most of them should follow/ inherit the behavior from `npm` for consistency's sake. I can say that this is more of a `pnpm` (and other `npm` like package managers) issue which is not something expected from `npm`.

References used in such research:

1. https://github.com/pnpm/pnpm/issues/2891
2. https://github.com/pnpm/pnpm/issues/2296
3. https://github.com/pnpm/pnpm/issues?q=is%3Aissue+postinstall+is%3Aclosed

**Comment by motss** [comment]
I've removed this in 7dd812e792f8f05d6c7d5ca182875d9ef647f234.
