### ISSUE TITLE
Postinstall error on ZSH console

### ISSUE THREAD

**Issue by nass600** [motss/normalize-diacritics#123]
### Description

Package `postinstall` script fails in ZSH console when installing the dependency through npm

### Expected outcome

Package successfully installed

### Actual outcome

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! normalize-diacritics@3.0.6 postinstall: `bash postinstall.bash`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the normalize-diacritics@3.0.6 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

### Steps to reproduce

1. Run `npm install normalize-diacritics`.

-->

### Versions of affected system

- **normalize-diacritics version**: 3.0.6
- **Node.js version**: v14.15.1
- **Platform details**: macOS Big Sur 11.6.4

**Comment by motss** [comment]
Closing this as 1fdd4a00d6044a097119091ac15c3175668e863e has resolved the issue.

**Comment by nass600** [comment]
Thanks for the quick reply. `v3.0.7` solved the issue 👍
