### ISSUE TITLE
bug: postinstall fails in pnpm-monorepo

### ISSUE THREAD

**Issue by christiantakle** [motss/normalize-diacritics#129]
The "postinstall" is specific to working on the package itself and not useful for consumers of the package.

Consider "prepare" instead? or maybe there is a better match: https://docs.npmjs.com/cli/v8/using-npm/scripts#life-cycle-scripts. You can also consider a custom bootstrap script for when you need to work on the package.

### Description

`postinstall` fails in a pnpm monorepo

### Expected outcome

That `normalize-diacritics` installs correctly

### Actual outcome
`<my-user>` and `<our-repo>` is  redacted information
```
...
node_modules/.pnpm/normalize-diacritics@3.0.11/node_modules/normalize-diacritics: Running postinstall script, failed in 481ms
.../node_modules/normalize-diacritics postinstall$ sh postinstall.sh
│ npm ERR! code ENOENT
│ npm ERR! syscall lstat
│ npm ERR! path /home/<my-user>/work/<our-repo>/lib
│ npm ERR! errno -2
│ npm ERR! enoent ENOENT: no such file or directory, lstat '/home/<my-user>/work/<our-repo>/lib'
│ npm ERR! enoent This is related to npm not being able to find a file.
│ npm ERR! enoent
│ npm ERR! A complete log of this run can be found in:
│ npm ERR!     /home/<my-user>/.npm/_logs/2022-11-08T09_59_58_504Z-debug-0.log
...
```

The line that triggers the error:
`postinstall.sh`
```
npx -y -- zx@latest ./postinstall.mjs
```

### Steps to reproduce
We run (in our monorepo)
`<repo>/package.json`
```
    "workspace--install": "git config  url.\"ssh://git@\".insteadOf git:// && pnpm recursive install --link-workspace-packages",
```

### Versions of affected system
* package: `normalize-diacritics@3.0.11`
* `pnpm --version` => 7.14.0
* `nix --version` => nix (Nix) 2.11.1
* platform: `Linux <my-hostname> 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 GNU/Linux`

**Comment by CanRau** [comment]
Just wanted to install the package and run into the same issue that I can't install because of the `postinstall` script failing

**Comment by christiantakle** [comment]
@CanRau

Temporary solutions while we wait for feedback.

* nuclear option: https://pnpm.io/cli/patch  (I did this)
* https://pnpm.io/package_json#pnpmneverbuiltdependencies (seems more correct, I did not try it)

**Comment by CanRau** [comment]
Thanks for the workarounds, still using yarn at the moment, maybe there would be options too but I think I have my string normalization in place already 🤓

**Comment by motss** [comment]
@christiantakle @CanRau Thanks for reporting this. The fix will shortly be ready.

**Comment by motss** [comment]
@christiantakle @CanRau Thanks for waiting for the fix. Please update to [`v3.0.12`](https://github.com/motss/normalize-diacritics/releases/tag/v3.0.12). 🙇
