### ISSUE TITLE
Consider limiting `input` type to `string`

### ISSUE THREAD

**Issue by harveysanders** [motss/normalize-diacritics#142]
### Description
The type for parameter `input` in `normalizeSync` implies that `undefined` and `null` are acceptable inputs. However, the first line of the function throws an error if the input is not a `string`. 

https://github.com/motss/normalize-diacritics/blob/main/src/normalize-sync.ts#L3-L6

I believe it would be more ergonomic to have TypeScript signal to the dev that only `string`s are acceptable.
In my opinion, TS is best suited to help devs avoid runtime errors by attempting to move common issues to compile-time errors. With this in mind, I think it would be more helpful to set `input` to  only `string`. 

```ts
export function normalizeSync(input: string): string {
  //....
}
```
That way we get type errors _before_ running the code:
```ts
/** @type {string | undefined | null} */
const input = getInputFromWherever();

normalizeSync(input);
              ^^^^
              // Argument of type 'string | null | undefined' 
              // is not assignable to parameter of type 'string'.
              // Type 'undefined' is not assignable to type 'string'.ts(2345)
```

What do you think?

Anyway, thanks for building this lib 🙂

**Comment by harveysanders** [comment]
If you agree, I'm happy to submit a PR : )

**Comment by motss** [comment]
@harveysanders Thanks for the feedback. I initially included null and undefined because of JavaScript being a dynamic language. I really like your explanation that TypeScript should tell the users the correct type and totally agree with your points.

Please help raise a PR to fix this.

**Comment by harveysanders** [comment]
@motss thanks for the quick response. Sounds good! I'll try to get one in next week : )

**Comment by harveysanders** [comment]
@motss I've just submitted a PR
